/*
class Autogenerated {
  int? id;
  String? userName;
  String? password;

  Autogenerated({this.id, this.userName, this.password});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userName = json['user_name'];
    password = json['password'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_name'] = this.userName;
    data['password'] = this.password;
    return data;
  }
}
 */